version: '2'

services:
  backend:
    volumes:
      - ./backend/bidsoup:/code/bidsoup/
    command: /bin/bash /code/start-dev.sh
    environment:
      - 'DEBUG=True'
    ports:
      - 8000:8000
      - 5678:5678

  frontend:
    volumes:
      - ./frontend/bidsoup/src:/usr/app/src/
      - ./frontend/bidsoup/public:/usr/app/public/
      - ./frontend/bidsoup/tslint.json:/usr/app/tslint.json
      - ./frontend/bidsoup/tsconfig.json:/usr/app/tsconfig.json
      - ./frontend/bidsoup/.env.development:/usr/app/.env.development
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  serv:
    ports:
      - 80:80
    volumes:
      - ./bidsoup_nginx_dev.conf:/etc/nginx/nginx.conf:ro
