version: '2'

services:
  backend:
    volumes:
      - ./backend/bidsoup:/code/bidsoup/
    command: /bin/bash /code/start-dev.sh
    environment:
      - 'DEBUG=True'
    ports:
      - 8000:8000
      - 5555:5555

  frontend:
    volumes:
      - ./frontend/bidsoup/src:/usr/app/src/
      - ./frontend/bidsoup/public:/usr/app/public/
      - ./frontend/bidsoup/tslint.json:/usr/app/tslint.json
      - ./frontend/bidsoup/tsconfig.json:/usr/app/tsconfig.json
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
