# Generated by Django 2.0.1 on 2018-02-09 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bids', '0001_initial'), ('bids', 'bidtask_to_bids')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bid_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('markup_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidTask')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('color', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('EA', 'Each'), ('PR', 'Pair'), ('FT', 'Linear Feet'), ('LFT', 'Linear Feet'), ('FT2', 'Square Feet'), ('FT3', 'Cubic Feet'), ('HR', 'Hour'), ('WK', 'Week')], default='EA', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='biditem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.Category'),
        ),
        migrations.AddField(
            model_name='biditem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bids.ItemType'),
        ),
        migrations.AddField(
            model_name='biditem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidTask'),
        ),
        migrations.AddField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Customer'),
        ),
        migrations.AddField(
            model_name='bidtask',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biditem',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bidtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidTask'),
        ),
    ]
