# Generated by Django 2.0.1 on 2018-02-10 03:49

from django.db import migrations, models
import django.db.models.deletion
from bids.models import Bid

# Initializes the category.bid to the most recently created bid
def assign_category_default(apps, schema_editor):
    Category = apps.get_model('bids', 'Category')
    Bid = apps.get_model('bids', 'Bid')
    latest_bid_id = Bid.objects.order_by('-created_on').values('id').first()['id']

    for row in Category.objects.all():
        row.bid_id = latest_bid_id
        row.save(update_fields=['bid'])

class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(assign_category_default),
        migrations.AlterField(
            model_name='category',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        )
    ]
