# Generated by Django 2.0.1 on 2018-02-13 02:39

from django.db import migrations, models
import django.db.models.deletion


# Initializes the category.bid to the most recently created bid
def assign_category_default(apps, schema_editor):
    Category = apps.get_model('bids', 'Category')
    Bid = apps.get_model('bids', 'Bid')
    latest_bid = Bid.objects.order_by('-created_on').values('id').first()

    if latest_bid:
        for row in Category.objects.all():
            row.bid_id = latest_bid['id']
            row.save(update_fields=['bid'])

    else:
        # No bid. Delete hanging categories.
        Category.objects.all().delete()


# Initializes the biditem.category to the most recently category for
# matching the same bid
def assign_biditem_defaults(apps, schema_editor):
    Category = apps.get_model('bids', 'Category')
    BidItem = apps.get_model('bids', 'BidItem')

    for item in BidItem.objects.all().order_by('bid'):
       cat = Category.objects.filter(bid=item.bid).first()
       item.category = cat
       item.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=assign_category_default,
        ),
        migrations.AlterField(
            model_name='category',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.RenameModel(
            old_name='ItemType',
            new_name='UnitType',
        ),
        migrations.RenameField(
            model_name='BidItem',
            old_name='item_type',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='biditem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biditem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bids.UnitType'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bids.Category'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=assign_biditem_defaults,
        ),
    ]
