# Generated by Django 2.0.1 on 2018-02-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_category_bid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemType',
            new_name='UnitType',
        ),
        migrations.RenameField(
            model_name='BidItem',
            old_name='item_type',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='biditem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biditem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bids.UnitType'),
        ),
    ]
