# Generated by Django 2.0.1 on 2018-04-14 03:30

from django.db import migrations, models
import django.db.models.deletion


# Gives all biditems without a parent the first BidTask from
# the same bid.
def assign_biditem_parent(apps, schema_editor):
    BidItem = apps.get_model('bids', 'BidItem')
    BidTask = apps.get_model('bids', 'BidTask')

    items = BidItem.objects.filter(parent=None)

    for row in items:
        task = BidTask.objects.filter(bid_id=row.bid_id).first()
        row.parent = task
        row.save(update_fields=['parent'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bidtask_recursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            code=assign_biditem_parent,
        ),
        migrations.AlterField(
            model_name='biditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidTask'),
        ),
    ]
