# Generated by Django 2.0.1 on 2018-07-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_force_biditem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
