# Generated by Django 2.0.1 on 2018-09-26 04:07

from django.db import migrations, models
import uuid

def assign_uuid(apps, schema_editor):
    for model in ['BidItem', 'BidTask', 'Category']:
        m = apps.get_model('bids', model)

        for row in m.objects.all():
            row.bid_uuid = row.bid.uuid
            row.save(update_fields=['bid_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_alter_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='bid_uuid',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidtask',
            name='bid_uuid',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='bid_uuid',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.RunPython(assign_uuid, reverse_code=migrations.RunPython.noop)
    ]
