# Generated by Django 2.0.1 on 2018-09-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0012_alter_pk_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='uuid',
            new_name='id',
        ),
    ]
