# Generated by Django 2.0.1 on 2018-09-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0013_rename_bid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bid_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='bid_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.AlterField(
            model_name='bidtask',
            name='bid_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
    ]
