# Generated by Django 2.0.1 on 2018-09-26 05:05

from django.db import migrations, models
import uuid


def assign_uuid(apps, schema_editor):
    for model in ['BidItem']:
        m = apps.get_model('bids', model)

        for row in m.objects.all():
            if row.unit_type:
                row.unit_type_uuid = row.unit_type.uuid
            else:
                row.unit_type_uuid = None

            row.save(update_fields=['unit_type_uuid'])



class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0015_rename_category_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='unit_type_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
            preserve_default=False
        ),
        migrations.RunPython(assign_uuid, reverse_code=migrations.RunPython.noop)
    ]
