# Generated by Django 2.0.1 on 2018-09-26 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0016_biditem_unit_type_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biditem',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='id',
        ),
        migrations.AlterField(
            model_name='biditem',
            name='unit_type_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameField(
            model_name='unittype',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='biditem',
            name='unit_type_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.UnitType', null=True, blank=True),
        ),
        migrations.RenameField(
            model_name='biditem',
            old_name='unit_type_uuid',
            new_name='unit_type'
        ),
    ]
