# Generated by Django 2.0.1 on 2018-10-05 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid

def assign_uuid(apps, schema_editor):
    for model in ['BidItem', 'BidTask']:
        m = apps.get_model('bids', model)

        for row in m.objects.all():
            if row.parent:
                row.parent_uuid = row.parent.uuid
            else:
                row.parent_uuid = None

            row.save(update_fields=['parent_uuid'])

def log(message):
    def fake_op(apps, schema_editor):
        print(message)
    return fake_op


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0018_awhoops'),
    ]

    operations = [
        # add the fields
        migrations.AddField(
            model_name='biditem',
            name='parent_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
            preserve_default=False
        ),
        migrations.AddField(
            model_name='bidtask',
            name='parent_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
            preserve_default=False
        ),
        # assign the fields
        migrations.RunPython(assign_uuid, reverse_code=migrations.RunPython.noop),
    ]
