# Generated by Django 2.0.1 on 2018-10-05 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid

def log(message):
    def fake_op(apps, schema_editor):
        print(message)
    return fake_op


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0019_biditem_parent_link'),
    ]

    operations = [
        migrations.RunPython(log('Remove all FKs'), reverse_code=migrations.RunPython.noop),
        # Remove all FKs to bidtask
        migrations.RemoveField(
            model_name='biditem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='bidtask',
            name='parent',
        ),
        migrations.RunPython(log('FKs removed'), reverse_code=migrations.RunPython.noop),
        # Remove bid task id field
        migrations.RemoveField(
            model_name='bidtask',
            name='id',
        ),
        migrations.AlterField(
            model_name='bidtask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameField(
            model_name='bidtask',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='biditem',
            name='parent_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidTask', null=True, blank=True),
        ),
        migrations.RenameField(
            model_name='biditem',
            old_name='parent_uuid',
            new_name='parent'
        ),
        migrations.AlterField(
            model_name='bidtask',
            name='parent_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidTask', null=True, blank=True),
        ),
        migrations.RenameField(
            model_name='bidtask',
            old_name='parent_uuid',
            new_name='parent'
        ),
    ]
