# Generated by Django 2.0.1 on 2018-10-05 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0020_biditem_parent_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidTask'),
        ),
        migrations.AlterField(
            model_name='bidtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bids.BidTask'),
        ),
    ]
