# Generated by Django 2.0.1 on 2018-10-05 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid

def assign_uuid(apps, schema_editor):
    for model in ['Bid']:
        m = apps.get_model('bids', model)

        for row in m.objects.all():
            row.customer_uuid = row.customer.uuid
            row.save(update_fields=['customer_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0021_fix_some_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='customer_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
            preserve_default=False
        ),
        # assign the fields
        migrations.RunPython(assign_uuid, reverse_code=migrations.RunPython.noop),
    ]
