# Generated by Django 2.0.1 on 2018-10-05 02:20

from django.db import migrations, models
import django.db.models.deletion
import uuid

def assign_uuid(apps, schema_editor):
    for model in ['BidItem']:
        m = apps.get_model('bids', model)

        for row in m.objects.all():
            row.category_uuid = row.category.uuid
            row.save(update_fields=['category_uuid'])




class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0023_customer_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='category_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=False),
            preserve_default=False
        ),
        # assign the fields
        migrations.RunPython(assign_uuid, reverse_code=migrations.RunPython.noop),
    ]
