# Generated by Django 2.0.1 on 2018-10-05 02:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


def log(message):
    def fake_op(apps, schema_editor):
        print(message)
    return fake_op


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0025_fix_categories'),
    ]

    operations = [
        # Remove biditem id field
        migrations.RemoveField(
            model_name='biditem',
            name='id',
        ),
        # Make uuid field the PK
        migrations.AlterField(
            model_name='biditem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        # Rename uuid to PK
        migrations.RenameField(
            model_name='biditem',
            old_name='uuid',
            new_name='id'
        ),
    ]
