# Generated by Django 2.0.1 on 2018-10-19 03:12

from django.db import migrations, models
import django.db.models.deletion

def create_dummy(apps, schema_editor):
    Account = apps.get_model('bids', 'Account')
    Bid = apps.get_model('bids', 'Bid')

    default_account = Account(name='Test Account', slug='test-account0')
    default_account.save()

    for b in Bid.objects.all():
        b.account = default_account
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0027_add_account_model'),
    ]

    operations = [
        migrations.RunPython(create_dummy, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bid',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Account'),
        ),
    ]
