# Generated by Django 2.0.1 on 2019-01-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0029_blank_key_for_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='taxable',
            field=models.BooleanField(default=False),
        ),
    ]
