# Generated by Django 2.0.1 on 2019-02-02 03:46

from django.db import migrations, models
import django.db.models.deletion

def set_user_to_account(apps, schema_editor):
    Account = apps.get_model('bids', 'Account')
    User = apps.get_model('bids', 'User')

    some_account = Account.objects.get()

    for u in User.objects.all():
        u.account = some_account
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0031_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bids.Account', null=True),
        ),
        migrations.RunPython(set_user_to_account)
    ]
