# Generated by Django 2.0.1 on 2019-02-23 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


def assign_units_to_categories(apps, schema_editor):
    UnitType = apps.get_model('bids', 'UnitType')

    for u in UnitType.objects.all():
        cat = u.biditem_set.first().category
        u.category = cat
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0032_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unittype',
            name='category',
            field=models.ForeignKey(default=uuid.uuid4(), on_delete=django.db.models.deletion.PROTECT, to='bids.Category'),
            preserve_default=False,
        ),
        migrations.RunPython(assign_units_to_categories),
        migrations.AlterField(
            model_name='unittype',
            name='unit',
            field=models.CharField(choices=[('EA', 'Each'), ('PR', 'Pair'), ('FT', 'Linear Feet'), ('LFT', 'Linear Feet'), ('FT2', 'Square Feet'), ('FT3', 'Cubic Feet'), ('HR', 'Hour'), ('WK', 'Week'), ('PHR', 'Person-Hour'), ('PWK', 'Person-Week')], default='EA', max_length=3),
        ),
    ]
