# Generated by Django 2.0.1 on 2019-03-28 03:20

from django.db import migrations, models
import django.db.models.deletion
import uuid

def set_customer_to_account(apps, schem_editor):
    Customer = apps.get_model('bids', 'Customer')

    for c in Customer.objects.all():
        related_bid = c.bids.first()
        c.account = related_bid.account
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0033_labor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(default=uuid.uuid4(), on_delete=django.db.models.deletion.CASCADE, to='bids.Account'),
            preserve_default=False,
        ),
        migrations.RunPython(set_customer_to_account, migrations.RunPython.noop)
    ]
