# Generated by Django 2.0.1 on 2019-04-29 02:13

from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import get_random_string
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0034_add_customer_account_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=get_random_string(32), max_length=32)),
                ('action', models.CharField(choices=[('CE', 'Confirm Email'), ('RS', 'Reset Password')], default='CE', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
