# Generated by Django 2.0.1 on 2019-10-14 02:41

from django.db import migrations, models
import django.db.models.deletion


# Initializes the biditem.category to the most recently category for
# matching the same bid
def assign_category_accounts(apps, schema_editor):
    Category = apps.get_model('bids', 'Category')
    Account = apps.get_model('bids', 'BidItem')

    for cat in Category.objects.all():
        cat.account = cat.bid.account
        cat.save(update_fields=['account'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0035_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Account'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=assign_category_accounts,
        ),
        migrations.AlterField(
            model_name='category',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.AddField(
            model_name='category',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by', to='bids.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Bid'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='link',
            field=models.CharField(max_length=32),
        ),
    ]
