# Generated by Django 2.0.1 on 2019-11-23 18:05

import bids.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0036_category_with_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Account'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='link',
            field=models.CharField(default=bids.models.generate_link_string, max_length=32),
        ),
    ]
