# Generated by Django 3.0.2 on 2020-01-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0040_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtask',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
