#!/usr/bin/env bash

# Get the environment variables that docker launced with (process 1)
. <(xargs -0 bash -c 'printf "export %q\n" "$@"' -- < /proc/1/environ)

python /code/bidsoup/manage.py clearsessions
